Repository IBM/aihwkit, pull requests merged in 2022-05, with the labels that each got.

#358 Multiple RNN Cells and Layers
  CHANGELOG.md
  examples/15_simple_lstm.py
  examples/15_simple_rnn.py
  src/aihwkit/nn/__init__.py
  src/aihwkit/nn/modules/base.py
  src/aihwkit/nn/modules/lstm.py
  src/aihwkit/nn/modules/rnn/__init__.py
  src/aihwkit/nn/modules/rnn/cells.py
  src/aihwkit/nn/modules/rnn/layers.py
  src/aihwkit/nn/modules/rnn/rnn.py
  tests/helpers/layers.py
  tests/test_conversions.py
  tests/test_layers_lstm.py
  tests/test_layers_rnn.py
Labels: enhancement

#373 GNU ABI autodetect and MKL libirc legacy dependence removed
  CMakeLists.txt
  cmake/Modules/FindMKL.cmake
  cmake/dependencies.cmake
Labels: build

#374 Added a fix in .travis.yml file for the last build error
  .travis.yml
  docs/img/hwa.jpg
  docs/img/hwa_added_noise.png
  docs/img/pcm_drift_model.png
  docs/requirements.txt
  docs/source/api/aihwkit.nn.modules.conv_mapped.rst
  docs/source/api/aihwkit.nn.modules.linear_mapped.rst
  docs/source/api/aihwkit.nn.modules.lstm.rst
  docs/source/api/aihwkit.nn.modules.rnn.cells.rst
  docs/source/api/aihwkit.nn.modules.rnn.layers.rst
  docs/source/api/aihwkit.nn.modules.rnn.rnn.rst
  docs/source/api/aihwkit.nn.modules.rnn.rst
  docs/source/api/aihwkit.nn.modules.rst
  docs/source/api_reference.rst
  docs/source/development_conventions.rst
  docs/source/examples.rst
  docs/source/hwa_training.rst
  docs/source/index.rst
  docs/source/pcm_inference.rst
  docs/source/using_pytorch.rst
  examples/README.md
  notebooks/examples/analog_training_LeNet5_hwa.ipynb
  src/aihwkit/nn/modules/rnn/layers.py
  src/aihwkit/nn/modules/rnn/rnn.py
  tests/README.md
Labels: documentation, build

#375 Fix documentation and example 15
  docs/source/api/aihwkit.simulator.tiles.base.rst
  docs/source/using_pytorch.rst
  examples/15_simple_rnn.py
  src/aihwkit/simulator/configs/devices.py
Labels: bug, documentation

#378 Updated the changelog
  CHANGELOG.md
Labels: documentation

#382 Change aihwkit version
  src/aihwkit/VERSION.txt
Labels: documentation
